spring:
  datasource:
    url:  jdbc:sqlserver://localhost:1433;databaseName=easylearn
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: create